#!/bin/sh

set -ax

SCRIPTS_DIR=$(dirname $0)

cd $SCRIPTS_DIR/..

CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o shorthand

docker build -t koki/shorthand:$(git rev-parse --short HEAD) .

echo "Built image succesfully"
echo "koki/shorthand:$(git rev-parse --short HEAD)"
